### ISSUE TITLE
Review report

### ISSUE THREAD

**Issue by fawda123** [tbep-tech/tbnmc-compliance-assessment-2022#1]
Maya and Ed, I've completed a draft of the 2022 compliance assessment report, updating all figures, text, and tables from last year's report.  Please review and edit as needed ([index.Rmd](https://github.com/tbep-tech/tbnmc-compliance-assessment-2022/blob/main/index.Rmd) file). Rendered version is [here](https://tbep-tech.github.io/tbnmc-compliance-assessment-2022/).

**Comment by esherwoo77** [comment]
I've reviewed and committed recommended text changes to the index.Rmd file.

**Comment by esherwoo77** [comment]
@fawda123 ,
@emseabee and I are both experiencing build fails with the updates we pushed. It looks related to the reference/link updates that we might have pushed?

**Comment by fawda123** [comment]
Caused by a dplyr update.  It's fixed now.
