### ISSUE TITLE
RA Table 2-6 Update Request

### ISSUE THREAD

**Issue by esherwoo77** [tbep-tech/tbnmc-compliance-assessment-2022#2]
This line/procedure needs updating to align with NMC reviewer comments. The result should be indicated, followed by the chl-a concentration (e.g. "No (7.1)" for OTB). Also, the conditional text will need to be updated when/if and OTB exceedance occurs during the 2022-2026 RA period. 
https://github.com/tbep-tech/tbnmc-compliance-assessment-2022/blob/f5e4a8899700dc196eb77f657079ea72d320e9fc/index.Rmd#L350

**Comment by fawda123** [comment]
@esherwoo77 should be fixed now.
